<HTML>
<b>Larissa Marques Fernandes n20 1B</b>
<p>/HTML>Olá,meu nome é Larissa Marques,esse é meu site.Nele,irei aprender e desenvolver meus projetos,aprender mais sobre o ramo de robótica e juntamente
com as minhas qualificações e aprendizados no ramo,irei cada dia mais me aprofundar no Github,na robótica e na minha vida profinalizante.
index.html
